name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      PRODUCTION_URL: "https://kind-water-03fb49d03.2.azurestaticapps.net/"
      STAGING_URL: "${{ format('https://kind-water-03fb49d03-{0}.westeurope.2.azurestaticapps.net/', github.event.number) }}"
                                      #url copy-pasted from Azure -> static web app -> custom domains
                                        #  delightful-wave-068d6ad03.2.azurestaticapps.net
                                      # MS docs about review url https://learn.microsoft.com/en-us/azure/static-web-apps/review-publish-pull-requests#review-changes
                                      # The URL is composed like this: https://<SUBDOMAIN-PULL_REQUEST_ID>.<AZURE_REGION>.azurestaticapps.net
      IS_PRODUCTION: "${{ startsWith(github.ref, 'refs/heads/main') }}" #https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_WATER_03FB49D03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/src/blog" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
          production_branch: "main"
          deployment_environment: "release"
        env: # Add environment variables here
          HUGO_ENVIRONMENT: "${{ env.IS_PRODUCTION == 'true' && 'production' || 'staging' }}"
          HUGO_baseURL: "${{ env.IS_PRODUCTION == 'true' && env.PRODUCTION_URL || env.STAGING_URL }}"
          HUGO_buildDrafts: "${{ env.IS_PRODUCTION == 'false' }}"
          HUGO_buildFuture: "${{ env.IS_PRODUCTION == 'false' }}"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_KIND_WATER_03FB49D03 }}
          action: "close"
